"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "blueprint.html"), "utf8");
const css = fs.readFileSync(path.join(root, "blueprint.css"), "utf8");
const script = fs.readFileSync(path.join(root, "blueprint.js"), "utf8");

const chapters = [...html.matchAll(/<article class="chapter(?: active)?" data-chapter="([^"]+)"/g)].map(match => match[1]);
assert.deepEqual(chapters, ["vision", "world", "loop", "session", "systems", "home", "slice", "decisions"], "蓝图应保持八章由全局到模块的讨论结构");
assert.match(html, /data-choice="homeForm"/, "蓝图应记录家园形式决策");
assert.match(html, /data-choice="lossRule"/, "蓝图应记录撤离损失决策");
assert.match(html, /data-editable/, "蓝图正文应支持直接编辑");
assert.match(html, /固定槽位居住舱/, "已确认的轻家园范围应写入垂直切片");
assert.match(html, /居民复杂寻路与生活模拟/, "蓝图应明确首版不制作复杂居民模拟");
assert.match(html, /不强迫经营，不阻塞下一次战斗/, "产品定位应说明战斗与轻家园的受众桥接原则");
assert.match(html, /核心玩法[\s\S]*肉鸽战斗与构筑/, "蓝图应将肉鸽战斗明确为核心玩法");
assert.match(html, /局内副玩法[\s\S]*搜打撤与货舱选择/, "搜打撤应明确归入局内副玩法");
assert.match(html, /局外副玩法[\s\S]*宠物轻家园/, "宠物家园应明确归入局外副玩法");
assert.match(html, /完全忽略家园，肉鸽本身也必须值得反复游玩/, "产品必须对不参与家园的肉鸽玩家独立成立");
assert.match(html, /结算页直接“再来一局”[\s\S]*家园始终可以跳过/, "家园不得阻塞战斗玩家快速重开");
assert.match(html, /家具制作不是进入新关卡或获得核心战斗内容的前置条件/, "家园装扮不得成为核心战斗内容门槛");
assert.match(html, /宠物本人穿舱外作业服[\s\S]*宠物驾驶小型战斗飞船[\s\S]*宠物驾驶步行机甲或探测车/, "蓝图应比较宠物、飞船和机甲三种局内玩家载体");
assert.match(html, /宠物开拓员[\s\S]*移民飞船“尾迹号”[\s\S]*星球地表与殖民遗迹/, "世界观应区分玩家主体、局外载体与战斗舞台");
assert.match(html, /低重力脉冲、离子风暴、陨石预警或引力异常[\s\S]*着陆信标、回收舱、扫描柱与撤离穿梭机[\s\S]*共享地表模块 \+ 一个地标 \+ 一个危险规则/, "地表关卡应以可复用的天象、任务物件和场景模块体现宇宙特性");
assert.match(html, /游戏内直接称“折叠式自动炮塔”[\s\S]*宠物背包投放的炮塔胶囊[\s\S]*装备卡、升级和战斗提示统一使用更直观的“自动炮塔”/, "固定炮塔应使用直观且符合星际开拓主题的装备名称");
assert.match(html, /采用轻度搜打撤/, "远征结构应记录已经确认的轻度搜打撤方案");
assert.match(html, /局内战斗值[\s\S]*带出物资值[\s\S]*局外经济值/, "蓝图应隔离三层数值体系");
assert.match(html, /永久伤害、生命和战斗倍率永远不因局外成长改变/, "局外成长不得改变永久战斗倍率");
assert.match(html, /只能完成特定任务解锁/, "仓库和货舱扩容必须由特定任务解锁");
assert.match(html, /普通货舱与安全槽均设固定上限/, "局内背包容量不得无限膨胀");
assert.match(html, /初始 4\+1、上限 6\+2/, "货舱数值应标明为可调整的原型占位值");
assert.match(html, /战斗中拾取密封物资箱[\s\S]*关卡结束统一开箱[\s\S]*撤离或继续深入/, "轻度搜打撤应有不打断战斗的完整原型流程");
assert.match(html, /回收零件[\s\S]*蓝图芯片[\s\S]*陈列遗物[\s\S]*居民信物/, "首版货物应保持四类清晰用途");
assert.match(html, /回收零件[\s\S]*1 格 · 可堆叠/, "常规材料应提供稳定且高占格效率的收益");
assert.match(html, /远征成功撤离是主要来源[\s\S]*普通敌人不直接喷洒零碎材料/, "局外材料应主要通过撤离获得且不干扰战斗拾取");
assert.match(html, /首版不拆成金属、木材、布料和电子件/, "首版材料系统应避免细分原料膨胀");
assert.match(html, /不承担每日维修费[\s\S]*永远不能购买永久伤害、生命或战斗倍率/, "回收零件不得形成维护负担或永久战力成长");
assert.match(html, /陈列遗物[\s\S]*2 格 · 可展示/, "大型收藏物应通过额外占格制造取舍");
assert.match(html, /货舱已满[\s\S]*永不自动删除已有货物/, "货舱替换必须由玩家明确决定");
assert.match(html, /重复蓝图自动转为少量材料/, "重复蓝图不应成为无效掉落");
assert.match(html, /经验升级[\s\S]*属性与被动技能[\s\S]*战斗装备箱[\s\S]*攻击武器、防御模块与部署装置[\s\S]*密封物资箱[\s\S]*可撤离货物/, "经验、外置装备与可撤离物资必须明确区分");
assert.match(html, /固定十关 × 前九关区域三选一[\s\S]*杀戮尖塔式可视化星图[\s\S]*降落后自由选择房间探索/, "蓝图应并列比较三种随机关卡结构");
assert.match(html, /竞技场 × 敌人生态 × 战斗规则 × 战斗奖励/, "首版随机性应来自可复用关卡模块组合");
assert.match(html, /撤离只开放在第 3、6、10 关/, "首版撤离节点应限制在三个阶段结点");
assert.match(html, /所有节点都能撤离[\s\S]*反复刷低风险前段/, "蓝图应解释禁止逐节点撤离的经济与策略原因");
assert.match(html, /data-choice="routeForm"/, "随机关卡结构应保留为可追踪决策记录");
assert.match(html, /前九关三选一区域[\s\S]*第十关固定 Boss/, "首版路线应明确最终 Boss 关不参与随机三选一");
assert.match(html, /ROUTE FORMAT · 已确认[\s\S]*方案 A · 已确认/, "已同意的十关区域选择方案应标记为确认");
assert.match(html, /废弃温室[\s\S]*坠毁通讯阵列[\s\S]*泄漏反应堆/, "蓝图应提供三张差异化区域卡示例");
assert.match(html, /威胁等级与区域名[\s\S]*敌人生态与场地规则[\s\S]*本局战斗收益[\s\S]*物资线索 · 非保证非专属/, "区域卡应优先展示战斗信息且不承诺专属物资");
assert.match(html, /每组三种动机[\s\S]*保底可打路线[\s\S]*软克制而非封锁[\s\S]*避免连续重复/, "随机路线生成应包含公平性和去重复约束");
assert.match(html, /任何卡都不能只提供家园收益/, "区域选择必须始终对纯战斗玩家有意义");
assert.match(html, /三选一不划分“家园关”和“纯战斗关”/, "区域选择不得将家园物资与纯战斗路线对立");
assert.match(html, /每关都可能出现密封物资箱[\s\S]*幸运提高普通敌人触发物资箱/, "所有区域都应受统一基础掉落与幸运规则影响");
assert.match(html, /区域线索只轻微调整权重，绝不排除其他类型/, "区域物资提示只能是非专属的轻微权重");
assert.match(html, /同阶段三张卡的基础物资期望保持一致/, "三选一区域的基础家园物资期望必须公平");
assert.match(html, /任务物品跟随任务条件结算[\s\S]*不会只藏在某一张区域卡/, "任务物品不得制造家园玩家必选路线");
assert.match(html, /每局保存路线种子与十关节点结果/, "随机关卡必须能够复现以支持测试");
assert.match(html, /关末只进入一个“整备舱”[\s\S]*不叠加多层弹窗/, "关末整备必须使用单一连续界面");
assert.match(html, /本关发生了什么[\s\S]*处理战斗构筑[\s\S]*处理可撤离物资[\s\S]*选择下一片区域/, "关末整备应保持明确的处理顺序");
assert.match(html, /没有升级可选[\s\S]*自动跳过步骤 01[\s\S]*物资直接放得下[\s\S]*自动开箱入舱/, "无决策内容不得制造额外操作");
assert.match(html, /居民特性与限制[\s\S]*攻击 · 生存 · 功能[\s\S]*共用槽位与实体挂载[\s\S]*攻击 · 防御 · 部署[\s\S]*等级与联动标签/, "完整构筑面板应展示角色、属性、统一外置装备预算与被动技能");
assert.match(html, /第 3、6 关先完成开箱[\s\S]*现在带回什么[\s\S]*继续会让哪些普通货舱处于风险/, "撤离节点必须直观比较带回收益与继续风险");
assert.match(html, /单屏单任务[\s\S]*不依赖悬停、拖拽或横向小按钮/, "移动端整备流程必须使用触控友好的单任务布局");
assert.match(html, /data-choice="levelTiming"[\s\S]*关末统一加点/, "已经确认的关末统一加点应记录为产品决策");
assert.match(html, /四层构筑各自负责不同问题[\s\S]*角色特性[\s\S]*基础属性[\s\S]*被动技能[\s\S]*外置装备/, "肉鸽构筑应将攻击、防御与部署装备合并为统一的第四层");
assert.match(html, /每个宠物提供两项优势、一项限制和一条改变规则的特性[\s\S]*引导方向但不禁止使用其他武器/, "角色应提供构筑偏好但不得硬锁武器");
assert.match(html, /攻击武器、防御模块和部署装置都必须实体可见[\s\S]*共用同一组装备槽[\s\S]*穿戴盔甲或护盾就会减少可携带火力/, "盔甲、护盾与武器必须竞争同一外置装备预算");
assert.match(html, /首版暂沿用六格[\s\S]*攻击武器[\s\S]*防御模块[\s\S]*部署装置[\s\S]*六格不是“六把枪 \+ 免费盔甲”/, "统一外置装备系统应包含三类装备并形成火力与生存取舍");
assert.match(html, /余震缓冲甲[\s\S]*堡垒叠层[\s\S]*脱落甲片[\s\S]*锚定姿态/, "外置重甲应在稳定减伤与有限甲片之间专精");
assert.match(html, /炽晶盾片[\s\S]*密集护环[\s\S]*折射刃缘[\s\S]*闭环封锁/, "实体盾片应通过拦截覆盖、反射和重构时间形成取舍");
assert.match(html, /棱镜屏障器[\s\S]*快充薄膜[\s\S]*过载棱镜[\s\S]*相位透支/, "能量屏障应在快速恢复、重击容量与一次保命之间取舍");
assert.match(html, /棘甲外骨骼[\s\S]*裂刺阵列[\s\S]*缓冲倒钩[\s\S]*裂火债务/, "棘甲应通过近身反击、接触减伤与延迟伤害形成取舍");
assert.match(html, /守望无人机[\s\S]*取消独立攻击[\s\S]*犬角色维修协议的跟随特效/, "原型守望无人机应退出免费攻击槽并改作不造成伤害的角色表现");
assert.match(html, /攻击武器允许同名多把[\s\S]*防御与炮塔同名唯一[\s\S]*开局装备也占格[\s\S]*满槽必须比较替换/, "攻击武器与防御部署装备应采用分类重复规则");
assert.match(html, /即将就绪[\s\S]*落点光圈[\s\S]*自动投放[\s\S]*固定攻击[\s\S]*“预告”只是落点提示/, "自动炮塔应以无需点击的落点提示解释自动投放");
assert.match(html, /角色特性[\s\S]*开局选择[\s\S]*基础属性[\s\S]*经验升级[\s\S]*外置装备[\s\S]*开局选择与装备箱/, "构筑矩阵应明确每一层的主要获取来源");
assert.match(html, /自动锁敌与精准规则[\s\S]*始终朝锁定目标或其预测位置攻击[\s\S]*不再让正常子弹无故偏离/, "自动锁敌武器不得用随机方向偏差表达精准度");
assert.match(html, /精准提高伤害下限、弱点收益和目标切换质量/, "精准属性应影响数值和目标判断而非弹道偏离");
assert.match(html, /攻击形态[\s\S]*战斗节奏[\s\S]*位置关系[\s\S]*公开联动/, "角色、技能和装备应通过公开标签形成构筑语法");
assert.match(html, /通用选项 \+ 当前联动 \+ 随机新方向/, "经验三选一应兼顾保底成长、构筑联动与转型随机性");
assert.match(html, /不因家园进度提高卡牌强度[\s\S]*蓝图扩大选择池/, "局外成长只能横向扩充构筑池");
assert.match(html, /关卡 1–3[\s\S]*关卡 4–6[\s\S]*关卡 7–9[\s\S]*关卡 10/, "十关构筑应具有明确的形成与检验节奏");
assert.match(html, /自动锁敌单射[\s\S]*霰弹与扇射[\s\S]*穿透与光束[\s\S]*环绕与回旋[\s\S]*追踪与弹射[\s\S]*爆炸与重型[\s\S]*固定炮塔/, "武器库应以攻击模式与覆盖短板形成差异");
assert.match(html, /基础强化 · 早期[\s\S]*专精分支 · 中期[\s\S]*超频改造 · 后期/, "武器升级应从有限纯收益进入互斥专精与风险超频");
assert.match(html, /技能点不升级武器[\s\S]*经验与技能点[\s\S]*只选属性和被动技能[\s\S]*普通装备箱[\s\S]*战斗中拾取，关末开出[\s\S]*同名攻击武器[\s\S]*增加副本或合并升级/, "技能点与关末处理的实体武器掉落必须使用不同成长通道");
assert.match(html, /余烬连弩 LV\.3 · A[\s\S]*余烬连弩 LV\.3 · B[\s\S]*炽晶盾片 LV\.2[\s\S]*折叠式自动炮塔 LV\.3/, "六格示例应展示同名攻击武器不同专精与唯一防御部署装备");
assert.match(html, /首次获得[\s\S]*装备一把 LV\.1[\s\S]*再次获得 · 有空格[\s\S]*再装一把 LV\.1[\s\S]*指定副本升 1 级[\s\S]*再次获得 · 已满格/, "同名攻击武器掉落应允许新增副本或指定副本升级");
assert.match(html, /LV\.1[\s\S]*获得实体武器[\s\S]*LV\.2[\s\S]*基础校准[\s\S]*LV\.3[\s\S]*互斥专精[\s\S]*LV\.4[\s\S]*深化专精[\s\S]*LV\.5[\s\S]*可选超频/, "单把武器应有五级封顶的身份、校准、专精和可选超频节奏");
assert.match(html, /LV\.5 封顶的是单个副本[\s\S]*攻击武器仍可在空槽中新增另一把同名 LV\.1[\s\S]*防御模块和自动炮塔则同名唯一/, "满级限制应作用于单个攻击武器副本而非同名数量");
assert.match(html, /余烬连弩[\s\S]*双生侧炮[\s\S]*星环刃[\s\S]*脉冲环[\s\S]*裂隙轨道枪[\s\S]*铸渣霰弹器[\s\S]*熔炉喷射器[\s\S]*电弧线圈[\s\S]*铸火折叠炮塔/, "九种现有实体装备应全部获得完整专精设计");
assert.match(html, /猎杀弩臂[\s\S]*分叉弩匣[\s\S]*红线索敌/, "余烬连弩应支持单体猎杀与分叉覆盖并提供风险超频");
assert.match(html, /交叉火控[\s\S]*侧翼警戒[\s\S]*全向齐射/, "双生侧炮应在集中火力和多向覆盖之间取舍");
assert.match(html, /贴身绞盘[\s\S]*彗尾外环[\s\S]*离心失控/, "星环刃应通过环绕半径与移动节奏形成路线差异");
assert.match(html, /锚定平台[\s\S]*前线节点[\s\S]*危险控制区/, "铸火折叠炮塔应保持固定部署身份并提供重型与多节点路线");
assert.match(html, /角色只表达偏好，不设置武器禁用[\s\S]*猫／狐狸[\s\S]*兔／仓鼠[\s\S]*犬／陆龟[\s\S]*刺猬[\s\S]*雪貂/, "九种武器应覆盖八角色偏好但不得硬锁角色武器");
assert.match(html, /频率 ↔ 单次威力[\s\S]*覆盖 ↔ 集中输出[\s\S]*射程 ↔ 近身效率[\s\S]*持续 ↔ 机动/, "武器风险应来自可预见的战斗取舍");
assert.match(html, /固定槽位与等级上限[\s\S]*同类加成先相加[\s\S]*软上限与最低间隔[\s\S]*禁止自我无限循环/, "武器数值系统必须防止无限堆叠与递归触发");
assert.match(html, /不是所有升级都必须有负面[\s\S]*早期需要有限的纯收益/, "武器成长应保留早期爽感而非滥用负面效果");
assert.match(html, /宠物必须影响肉鸽对局，不只是外观与动画差异/, "可玩宠物应具有真实的战斗身份");
assert.match(html, /优势、限制和特殊规则选择后整局固定[\s\S]*不因家园升级而变强/, "宠物优劣势必须固定且不受局外永久强化");
assert.match(html, /基础数值可以不同[\s\S]*核心辨识度来自规则特性/, "宠物可有适度属性差异但不应只靠数值区分");
assert.match(html, /至少支持两类武器和两条可行构筑/, "每个宠物角色不得只有唯一解构筑");
assert.match(html, /皮肤、服装、颜色和动画不带属性/, "宠物外观装扮不得携带战斗数值");
assert.match(html, /data-choice="petImpact"/, "宠物战斗影响应作为可追踪产品决策");
assert.match(html, /PLAYABLE PET POLICY · 已确认/, "用户确认后宠物战斗规则应更新为已确认");
assert.match(html, /猫 \/ 瞭望员[\s\S]*犬 \/ 工程师[\s\S]*兔 \/ 环刃舞者/, "蓝图应设计三个定位不同的起始宠物角色");
assert.match(html, /猎手标记[\s\S]*路线 A：重击／穿透／弱点爆发[\s\S]*路线 B：速射／追踪／连续收割/, "猫角色应同时支持重击和速射构筑");
assert.match(html, /维修协议[\s\S]*路线 A：炮塔／光束／固定阵地[\s\S]*路线 B：重型近战／护甲／反击/, "犬角色应同时支持阵地和前线构筑");
assert.match(html, /疾行节拍[\s\S]*路线 A：环绕／回旋／持续移动[\s\S]*路线 B：爆炸／重击／蓄节拍双发/, "兔角色应同时支持移动和蓄力构筑");
assert.match(html, /垂直切片[\s\S]*先完整打磨 3 个起始宠物[\s\S]*内容首版[\s\S]*保留 8 个可玩宠物/, "蓝图应区分三角色垂直切片与八角色内容首版");
assert.match(html, /仓鼠 \/ 弹幕手[\s\S]*陆龟 \/ 黑曜壁垒[\s\S]*狐狸 \/ 裂隙学者[\s\S]*雪貂 \/ 荒原拾荒者[\s\S]*刺猬 \/ 裂火狂战士/, "现有五套额外角色机制应映射为可解锁宠物");
assert.match(html, /后解锁不等于更强[\s\S]*相同角色预算和永久数值红线/, "可解锁角色必须是横向玩法而非强度阶梯");
assert.match(html, /共用 3 套体型动画骨架[\s\S]*独立制作轮廓、头尾、装备附件、待机和规则特效/, "八角色美术应通过共享骨架控制单人开发工作量");
assert.match(html, /八名角色共享相同的基础密封物资期望/, "宠物角色不得成为家园物资产出的长期必选项");
assert.match(html, /data-choice="rosterSize"/, "内容首版角色数量应作为可追踪产品决策");
assert.match(html, /新增动物居民 ≠ 必须新增可玩角色[\s\S]*可以共享武器与构筑标签[\s\S]*不能同时共享“主要触发条件”和“主要收益循环”/, "新增动物应与可玩角色分层，重复角色应回退为居民或皮肤");
assert.match(html, /八角色玩法占位图[\s\S]*猫 · 瞭望员[\s\S]*犬 · 工程师[\s\S]*兔 · 环刃舞者[\s\S]*仓鼠 · 弹幕手[\s\S]*陆龟 · 黑曜壁垒[\s\S]*狐狸 · 裂隙学者[\s\S]*雪貂 · 荒原拾荒者[\s\S]*刺猬 · 裂火狂战士/, "蓝图应追踪当前八角色的触发、转化与代价占位");
assert.match(html, /召唤物编队与指令[\s\S]*元素／异常状态转化[\s\S]*完美闪避或格挡时机[\s\S]*武器切换的节奏连段/, "蓝图应为未来可玩角色保留未使用的设计空间");
assert.match(html, /七项全部成立[\s\S]*不用动物名，也能用一句话说清战斗身份[\s\S]*至少支持两类武器与两条可行构筑路线[\s\S]*复用统一事件钩子/, "未来可玩角色必须通过玩法、构筑与实现准入检查");
assert.match(html, /角色规则 = 触发事件 \+ 条件 \+ 效果 \+ 明示代价[\s\S]*onAttack · onKill · onMove · onGuardTrigger · onReroll · onPickup · onLowHealth · onDeploy[\s\S]*角色配置集中在数据表/, "角色系统应采用统一事件钩子与数据驱动配置，避免散落特例");
assert.match(html, /新角色必须同时获得足够支撑两条路线的新武器、被动或敌人环境/, "新增可玩角色必须有配套内容支撑两条路线");
assert.match(html, /data-choice="futurePetRule"[\s\S]*居民与可玩角色分层/, "未来新增动物的角色规则应作为可追踪产品决策");
assert.match(html, /data-choice="futurePetRule"[\s\S]*决策 08 · 已确认[\s\S]*居民与可玩角色分层[\s\S]*已确认/, "继续设计后应确认居民与可玩角色分层原则");
assert.match(html, /data-choice="weaponSpecTiming"[\s\S]*三级专精五级可选超频/, "武器专精节奏应作为下一项可追踪产品决策");
assert.match(html, /data-choice="weaponSpecTiming"[\s\S]*决策 09 · 初步确认[\s\S]*三级专精五级可选超频[\s\S]*初步确认/, "武器专精节奏应记录为初步确认");
assert.match(html, /data-choice="equipmentSlots"[\s\S]*决策 10 · 已确认[\s\S]*共用外置装备槽[\s\S]*已确认/, "外置盔甲、护盾与武器共用槽位应记录为已确认决策");
assert.match(html, /data-choice="combatAvatar"[\s\S]*决策 11 · 已确认[\s\S]*宠物舱外地表战斗[\s\S]*已确认/, "宠物舱外地表战斗应记录为已确认的玩家载体");
assert.match(html, /data-choice="sentryControl"[\s\S]*提示后自动投放当前位置[\s\S]*增加主动投放按钮[\s\S]*完全随机自动布置/, "自动炮塔投放方式应作为下一项可追踪产品决策");
assert.match(html, /data-choice="duplicateEquipment"[\s\S]*攻击武器可重复防御部署唯一[\s\S]*所有装备都同名唯一[\s\S]*所有装备都允许重复/, "同名装备重复规则应作为可追踪产品决策");
assert.match(html, /产品与核心玩法约 75%[\s\S]*实现规格约 45%[\s\S]*1 周技术尖刺 \+ 3 关切片/, "蓝图应区分产品策划成熟度与可执行实现规格");
assert.match(html, /战斗合同[\s\S]*内容数据表[\s\S]*界面状态流[\s\S]*数据与存档边界[\s\S]*技术验收线/, "开工门槛应包含五份薄实现规格");
assert.match(html, /A0 · 技术尖刺[\s\S]*1 宠物 × 2 武器 × 2 敌人[\s\S]*A1 · 可玩垂直切片[\s\S]*3 关微型远征[\s\S]*A2 · 内容首版[\s\S]*扩成完整十关/, "新原型应从技术尖刺逐步扩展到三关切片和十关内容首版");
assert.match(html, /Cocos Creator 3\.8 LTS \+ TypeScript[\s\S]*现有 HTML／JS 原型保留为数值与机制实验台/, "蓝图应记录推荐生产技术栈与旧原型定位");
assert.match(html, /Cocos Creator \+ TS[\s\S]*Unity \/ 团结引擎 \+ C#[\s\S]*LayaAir \+ TypeScript[\s\S]*Godot \+ GDScript[\s\S]*原生 HTML \/ Canvas \/ JS/, "技术决策应比较五类候选方案");
assert.match(html, /Web 测试版[\s\S]*微信小游戏[\s\S]*抖音小游戏[\s\S]*Android \/ iOS App[\s\S]*PC 客户端/, "发布路线应按验证成本逐步扩展平台");
assert.match(html, /WebGL 不等于小游戏“一键换壳”[\s\S]*登录、广告、支付、分享、云存档/, "蓝图应明确小游戏仍需渠道适配层");
assert.match(html, /data-choice="productionEngine"[\s\S]*Cocos Creator 3\.8 \+ TypeScript/, "生产技术栈应作为可追踪产品决策");
assert.match(html, /data-choice="releaseSequence"[\s\S]*Web到微信到抖音到原生App/, "发布验证顺序应作为可追踪产品决策");
assert.match(html, /data-choice="prototypeDepth"[\s\S]*技术尖刺后做三关切片/, "新原型深度应作为可追踪产品决策");
assert.match(script, /localStorage\.setItem/, "讨论状态应保存在当前浏览器");
assert.match(script, /exportDiscussion/, "蓝图应能导出讨论稿");
assert.match(css, /@media\(max-width:760px\)/, "蓝图应提供移动端布局");

console.log("Blueprint test passed: chapters, editing, decisions, persistence and responsive layout.");
