"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "blueprint.html"), "utf8");
const css = fs.readFileSync(path.join(root, "blueprint.css"), "utf8");
const script = fs.readFileSync(path.join(root, "blueprint.js"), "utf8");

const chapters = [...html.matchAll(/<article class="chapter(?: active)?" data-chapter="([^"]+)"/g)].map(match => match[1]);
assert.deepEqual(chapters, ["vision", "world", "loop", "session", "systems", "home", "slice", "decisions"], "蓝图应保持八章由全局到模块的讨论结构");
assert.match(html, /data-choice="homeForm"/, "蓝图应记录家园形式决策");
assert.match(html, /data-choice="lossRule"/, "蓝图应记录撤离损失决策");
assert.match(html, /data-editable/, "蓝图正文应支持直接编辑");
assert.match(html, /固定槽位居住舱/, "已确认的轻家园范围应写入垂直切片");
assert.match(html, /居民复杂寻路与生活模拟/, "蓝图应明确首版不制作复杂居民模拟");
assert.match(html, /不强迫经营，不阻塞下一次战斗/, "产品定位应说明战斗与轻家园的受众桥接原则");
assert.match(html, /核心玩法[\s\S]*肉鸽战斗与构筑/, "蓝图应将肉鸽战斗明确为核心玩法");
assert.match(html, /局内副玩法[\s\S]*搜打撤与货舱选择/, "搜打撤应明确归入局内副玩法");
assert.match(html, /局外副玩法[\s\S]*宠物轻家园/, "宠物家园应明确归入局外副玩法");
assert.match(html, /完全忽略家园，肉鸽本身也必须值得反复游玩/, "产品必须对不参与家园的肉鸽玩家独立成立");
assert.match(html, /结算页直接“再来一局”[\s\S]*家园始终可以跳过/, "家园不得阻塞战斗玩家快速重开");
assert.match(html, /家具制作不是进入新关卡或获得核心战斗内容的前置条件/, "家园装扮不得成为核心战斗内容门槛");
assert.match(html, /采用轻度搜打撤/, "远征结构应记录已经确认的轻度搜打撤方案");
assert.match(html, /局内战斗值[\s\S]*带出物资值[\s\S]*局外经济值/, "蓝图应隔离三层数值体系");
assert.match(html, /永久伤害、生命和战斗倍率永远不因局外成长改变/, "局外成长不得改变永久战斗倍率");
assert.match(html, /只能完成特定任务解锁/, "仓库和货舱扩容必须由特定任务解锁");
assert.match(html, /普通货舱与安全槽均设固定上限/, "局内背包容量不得无限膨胀");
assert.match(html, /初始 4\+1、上限 6\+2/, "货舱数值应标明为可调整的原型占位值");
assert.match(html, /战斗中拾取密封物资箱[\s\S]*关卡结束统一开箱[\s\S]*撤离或继续深入/, "轻度搜打撤应有不打断战斗的完整原型流程");
assert.match(html, /回收零件[\s\S]*蓝图芯片[\s\S]*陈列遗物[\s\S]*居民信物/, "首版货物应保持四类清晰用途");
assert.match(html, /回收零件[\s\S]*1 格 · 可堆叠/, "常规材料应提供稳定且高占格效率的收益");
assert.match(html, /远征成功撤离是主要来源[\s\S]*普通敌人不直接喷洒零碎材料/, "局外材料应主要通过撤离获得且不干扰战斗拾取");
assert.match(html, /首版不拆成金属、木材、布料和电子件/, "首版材料系统应避免细分原料膨胀");
assert.match(html, /不承担每日维修费[\s\S]*永远不能购买永久伤害、生命或战斗倍率/, "回收零件不得形成维护负担或永久战力成长");
assert.match(html, /陈列遗物[\s\S]*2 格 · 可展示/, "大型收藏物应通过额外占格制造取舍");
assert.match(html, /货舱已满[\s\S]*永不自动删除已有货物/, "货舱替换必须由玩家明确决定");
assert.match(html, /重复蓝图自动转为少量材料/, "重复蓝图不应成为无效掉落");
assert.match(html, /战斗强化宝箱[\s\S]*本局武器、技能与数值[\s\S]*密封物资箱[\s\S]*可撤离货物/, "局内强化宝箱与可撤离物资箱必须明确区分");
assert.match(html, /固定十关 × 前九关区域三选一[\s\S]*杀戮尖塔式可视化星图[\s\S]*降落后自由选择房间探索/, "蓝图应并列比较三种随机关卡结构");
assert.match(html, /竞技场 × 敌人生态 × 战斗规则 × 战斗奖励/, "首版随机性应来自可复用关卡模块组合");
assert.match(html, /撤离只开放在第 3、6、10 关/, "首版撤离节点应限制在三个阶段结点");
assert.match(html, /所有节点都能撤离[\s\S]*反复刷低风险前段/, "蓝图应解释禁止逐节点撤离的经济与策略原因");
assert.match(html, /data-choice="routeForm"/, "随机关卡结构应保留为可追踪决策记录");
assert.match(html, /前九关三选一区域[\s\S]*第十关固定 Boss/, "首版路线应明确最终 Boss 关不参与随机三选一");
assert.match(html, /ROUTE FORMAT · 已确认[\s\S]*方案 A · 已确认/, "已同意的十关区域选择方案应标记为确认");
assert.match(html, /废弃温室[\s\S]*坠毁通讯阵列[\s\S]*泄漏反应堆/, "蓝图应提供三张差异化区域卡示例");
assert.match(html, /威胁等级与区域名[\s\S]*敌人生态与场地规则[\s\S]*本局战斗收益[\s\S]*物资线索 · 非保证非专属/, "区域卡应优先展示战斗信息且不承诺专属物资");
assert.match(html, /每组三种动机[\s\S]*保底可打路线[\s\S]*软克制而非封锁[\s\S]*避免连续重复/, "随机路线生成应包含公平性和去重复约束");
assert.match(html, /任何卡都不能只提供家园收益/, "区域选择必须始终对纯战斗玩家有意义");
assert.match(html, /三选一不划分“家园关”和“纯战斗关”/, "区域选择不得将家园物资与纯战斗路线对立");
assert.match(html, /每关都可能出现密封物资箱[\s\S]*幸运提高普通敌人触发物资箱/, "所有区域都应受统一基础掉落与幸运规则影响");
assert.match(html, /区域线索只轻微调整权重，绝不排除其他类型/, "区域物资提示只能是非专属的轻微权重");
assert.match(html, /同阶段三张卡的基础物资期望保持一致/, "三选一区域的基础家园物资期望必须公平");
assert.match(html, /任务物品跟随任务条件结算[\s\S]*不会只藏在某一张区域卡/, "任务物品不得制造家园玩家必选路线");
assert.match(html, /每局保存路线种子与十关节点结果/, "随机关卡必须能够复现以支持测试");
assert.match(script, /localStorage\.setItem/, "讨论状态应保存在当前浏览器");
assert.match(script, /exportDiscussion/, "蓝图应能导出讨论稿");
assert.match(css, /@media\(max-width:760px\)/, "蓝图应提供移动端布局");

console.log("Blueprint test passed: chapters, editing, decisions, persistence and responsive layout.");
